package userscript;

class MetaGenerator extends Generator
{
    public function generate()
    {
        var out = "// ==UserScript==\n";

        for (m in this.meta) {
            if (!Lambda.has(Constants.USERSCRIPT_VARIABLES, m.name))
                continue;

            for (value in m.values) {
                out += "// @" + m.name + " " + value + "\n";
            }
        }

        out += "// ==/UserScript==\n\n";

        out += "// THIS FILE IS AUTOGENERATED, PLEASE DO NOT MODIFY!\n";
        out += "// If you want to make changes, please look into the\n";
        out += "// UserScript block above to get more information on\n";
        out += "// how to obtain the source code or make changes.\n";

        return out;
    }
}
