package userscript;

import haxe.macro.Expr;

class MetaGenerator extends Generator
{
    public function generate()
    {
        var out = "// ==UserScript==\n";

        for (m in this.meta) {
            var name:String = m.name;

            if (!Lambda.has(Constants.USERSCRIPT_VARIABLES, name))
                continue;

            for (p in m.params) {
                var values = this.get_values(p.expr);
                for (value in values) {
                    out += "// @" + name + " " + value + "\n";
                }
            }
        }

        out += "// ==/UserScript==\n\n";

        out += "// THIS FILE IS AUTOGENERATED, PLEASE DO NOT MODIFY!\n";
        out += "// If you want to make changes, please look into the\n";
        out += "// UserScript block above to get more information on\n";
        out += "// how to obtain the source code or make changes.\n";

        return out;
    }
}
